travis:
  secure:
    BINSTAR_TOKEN: Tfhczw30teNmuJk9W+pb1+qQkl9RVgHsU/1AnW5KYoe7K3M1/M5pDzbCXGZUbyLzg4peX0ekiO1Zb6HntQkQfvWUR4kYyo9qKTr1jSIRaoKaRG56GYgh4WjjtnI+GkwiyP2gX6pfVOFyMVxl3yBw/QokHS/cOMSG6IIhdrRC+7RCblg3/Z2Q22oP1FTlLoIP2LKkw4PEttgazxmWmrk3FmctTJmA/vlk8oj4OQKCEtrcP8SGD/ladgzJvQc8uh//cNxILrtyE8Y63NsMRIy9XDXo3tOxS2OXr2hDOl8wjav/NKYQSB9RBCX3S9Tntt9YG2cxqdG5NJ/rDABi6powh2qKVDTWhJlg8+r9buQOPdAUeHAUx5YWHQ8yc0L2tIOVzvk91ze9Wm9cq4vEF0hfOWHvOHPFW0aG45cwv36m9eFtZpExi/Jqsca8RwRe9BdgxJhN5EQXnrpBCDWWVs8tAoxI9rSjn9J4qCA6+5invyOEdGpFHel8mCZbfNeiSXD8Qg6j70nyacxy181pFDTln6VvbZIOWR1lnvLv0AbKAMczjB6Wx4A9LDrhMysZKbha9m3mkRW2BYJnDtQjLDnZ/pJh710wb5fKZ4nVNWLYvuFSdfy4EHcts0HRsITFlpXxc1rQCTpF8QSJX28UzCCUh0ijFLXLEjDIvXRDrL728vs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
