travis:
  secure:
    BINSTAR_TOKEN: ESoiVRPiykOZeY81iGedplimmTRrEF8E+nwxUkVSt0PWMSdwQ55fOrUOXuOcY4Q7RJ73kCdtUhgw/r2+t0rTfNVpXk0IcE6RSdQOROfKZlCJs3OpsJImfKeuTxQdCNTwUOms4QDL2GQzn/QpSqLQSJyjrbLrHM+pCbSW8+DoSM9G7Ci1htddxr9wRwR/8q1MMXtxH+Xx3IgSFFonJE0S35zcSxsewy/u4kF+Oefe/IN5k8Mbzb2E9ibKYzcL3cybxhtFu4pOblLVjvOEj9FJgio1jpKDt+qOfEceAleH7yebzTEJnJS49Adot4RcE1YkpJU3c6crHxBSjWbTJeLTfED++/86kzfl5epYlpudIHcLi2Qti6L+1wve+NBClW+spKJV0dxPbMPFZHf2vERa13QkSm5aPxULmakeo9ZGP4LpG/a6o/j2eU/uCBrsvYuF5ABFYwvuMKDLAqQzTfjQ31k1DcPcfwx8oYiWcbb/mlyH4DPmfMTlDUt3kjqwvnPykkiklNj10Y2H8FZHUu3YZQCj2slsiwZrO2eqB+5KVwyOqdZEbTOn8w6kfW17OiJz/xmz940CgGd5yT2mA490IEwvY9bAR83LEtEsFwaCR58u8oPUDoJKcZzr9WmuXrr9hwoy2lvze+jWwlq47ghiMk67OlT73b1+j7kpMbkE5/o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
