travis:
  secure:
    BINSTAR_TOKEN: YM1CNIeTOsO0FbQKWK02093lgS8WtW1fNWSUtdP3y3mKtPGv0lG5hV9DAP9gPBLZa9KJ53sWO1Y+TOOdOn3Gi5Ef9ngoNfswO73ExQfxQS9Qtg3NS9CoOiZmIgizP1k2qyw7qOHHe9RvVXFy4Ga3d7INF6YcoiI2C7WBC/rhosPV4es3FZyNmAYffXsRgFB8F+Y7s94YukiuhvzbFQK4x4CsBMIb8tKOyqYISgxFPgn8FG+vLzII1PHdpS5/Ti8ZPTx/faeGEo7356/Y5PYB6kvXzMRHtxzSqdDluasnbdylcLree+CqnWJJM+kIGCxNc35GDhJGPlrHY/vHbDHcVh0hUzKe+T0Z2AkvYwPdLz5g+vkMtkI13qp8j3o1JggQ+yTV5opJH4btodLwUctBLk9rPVkKOtGMOmyk8rxilZQExoYElVrAkDixGEN2AXziVOUMN8Gb8zm4sD7cCnT5aRFDDTQthldSqYvFG+CfxXwU+qRldWjuMhkN7SACdW3C+R5DJvFnrxpRcimOBkFW7083PS1ebe7+1/OoxqL2e1slkM96Mwe2d4o0oA8zryPBwqxN5K431IZj1g4UdIRO2T1Bojv2s1bTz9/7A4roqNP2pj3AsCq1/oQlOIE7Jw2EmrlTyOJa5knLjWYCBUGI4AM3CYTafSDnDYyN8aztGnM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
