travis:
  secure:
    BINSTAR_TOKEN: ciC06HXducVrzSRroFgEsoQrT6O5xSTRIrS6VR7vhKWpQF8N7qrB9IJdlpV9+GSE4SrU6ONcx13wakz/lN6L4VW4iVEEt3Cnt9M4tb9xdj6m5BYn4YTn1ePnn7pIhEPsIOR/9DyVHfEZ4HmhXqp7B8Cd1DlR45naRwyS2lJUorEqzzc+gv33XSac8IypBozO4XYFlsBh5847mY9Crz4lbvrzsldDIbmcqck6AV0ohjDcpx2THeki0yvd5KA8BSJV4Hk6y501BHet1ttxxUgQF1YkWhPxyUP6sB4t5+g90tRQqY9nyLT0kzQ3o9NqTuqhBPSWQ7JvsahogJQ8cPF1vr1acc4s79679aehegt+2/yD+TgQ3BrKaJ/in3XNgfIBTtl+9xomY95bkzUSG+i8EYmnwnQ1XxPckgwPufNliLsrBa/G/Qj3uLjNMXw1NrSPg4DxaZiCCJRiz168cLv0+Hx8NyPlpmQnAVxxUEzc4gjclBSIohokoFgJ0qQ3GDBQHoCWD5ZD9KFViWLiM3hxBHIliO4hsFBmPifR0kcLbj4u5MnZq+DfzSKimAlqh5IFAYhq/nRtWLMhQTsRSxglFfh9nZTozNMcPl2Qkl4tvE8UZHzvodHM9nlBxe9eaKEXH9lmRqgtzLU034AbHLyRKWOTYw9W6UTQu8xyZAZNuqQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
